name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up promu
        run: go install github.com/prometheus/promu@v0.12.0

      - name: Build
        run: promu crossbuild -v

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/zenhub_exporter:${{ github.ref }}

      - run: promu crossbuild tarballs
      - run: promu checksum .tarballs

      - name: Create Release
        run: promu release .tarballs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
